curl -XPOST -H "Content-Type: application/json" https://localhost:5001/robots -w "\n" -k --data '{"loadId": 231, "x": 5, "y": 3}'
curl -XPOST -H "Content-Type: application/json" https://localhost:5001/robots -w "\n" -k --data '{"loadId": 232, "x": 50, "y": 30}'
curl -XPOST -H "Content-Type: application/json" https://localhost:5001/robots -w "\n" -k --data '{"loadId": 233, "x": 420, "y": 300}'
curl -XPOST -H "Content-Type: application/json" https://localhost:5001/robots -w "\n" -k --data '{"loadId": 234, "x": 0, "y": 0}'
curl -XPOST -H "Content-Type: application/json" https://localhost:5001/robots -w "\n" -k --data '{"loadId": 235, "x": 100, "y": 100}'
curl -XPOST -H "Content-Type: application/json" https://localhost:5001/robots -w "\n" -k --data '{"loadId": 236, "x": -40, "y": -10}'
